export const tableData = [
  { id: 1, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 2, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 3, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 4, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 5, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 6, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 7, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 8, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 9, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 10, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 11, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 12, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 13, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 14, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 15, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 16,name: "Tom", age: 26, gender: "Male", designation: "Front End Developer"},
  { id: 17, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 18, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 19, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 20,  name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer"},
  { id: 21, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 22, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 23, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 24, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 25, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 26, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 27, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 28, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 29, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 30, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 31, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 32, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 33, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 34, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 35, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 36,name: "Tom", age: 26, gender: "Male", designation: "Front End Developer"},
  { id: 37, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 38, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 39, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 40,  name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer"},
  { id: 41, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 42, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 43, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 44, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 45, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 46, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 47, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 48, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 49, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 50, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 51, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 52, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 53, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 54, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 55, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 56,name: "Tom", age: 26, gender: "Male", designation: "Front End Developer"},
  { id: 57, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 58, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 59, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 60,  name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer"},
  { id: 61, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 62, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 63, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 64, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 65, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 66, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 67, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 68, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 69, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 70, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 71, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 72, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 73, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 74, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 75, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 76,name: "Tom", age: 26, gender: "Male", designation: "Front End Developer"},
  { id: 77, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 78, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 79, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 90,  name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer"},
  { id: 81, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 82, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 83, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 84, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 85, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 86, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 87, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 88, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 89, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 90, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 91, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 92, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 93, name: "Adharsh", age: 22, gender: "Male", designation: "Full Stack(React + Java) Developer" },
  { id: 94, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 95, name: "Steve", age: 27, gender: "Female", designation: "UI/UX Designer" },
  { id: 96,name: "Tom", age: 26, gender: "Male", designation: "Front End Developer"},
  { id: 97, name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer" },
  { id: 98, name: "Morgan", age: 24, gender: "Female", designation: "React Developer" },
  { id: 99, name: "Tom", age: 26, gender: "Male", designation: "Front End Developer" },
  { id: 100,  name: "Michal", age: 24, gender: "Male", designation: "Full Stack Engineer"},
]


export const productList = [
    {
      id: 1,
      name : "Destiny Fashion Men's Regular Fit Shirt",
      main_image: "https://m.media-amazon.com/images/I/71qTbVnVZZL._UY879_.jpg",
      description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      price : 3000
    },

    {
        id: 2,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/411z7GwShzL.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 2500
      },

      {
        id: 3,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/8193GX9rftL._UY879_.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 1200
      },

      {
        id: 4,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/414H24Gi5fS._AC_SR480,600_.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 2100
      },

      {
        id: 5,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/51rQSKZtS+L.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 1500
      },
      {
        id: 6,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/411z7GwShzL.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 2500
      },

      {
        id: 7,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/8193GX9rftL._UY879_.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 1200
      },

      {
        id: 8,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/414H24Gi5fS._AC_SR480,600_.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 2100
      },
      
      {
        id: 9,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/414H24Gi5fS._AC_SR480,600_.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 2100
      },

      {
        id: 10,
        name : "Destiny Fashion Men's Regular Fit Shirt",
        main_image: "https://m.media-amazon.com/images/I/51rQSKZtS+L.jpg",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        price : 1500
      },
      
  ]

